name: deleteAllClusters
description: Deletes all apps and clusters in a project
author: Realm
inputs:
  atlasUrl:
    required: false
    description: The Atlas url - e.g. https://cloud-qa.mongodb.com.
  realmUrl:
    required: false
    description: The MongoDB Realm url - e.g. https://realm-qa.mongodb.com.
  projectId:
    required: true
    description: The Atlas project Id.
  apiKey:
    required: true
    description: The public API key.
  privateapiKey:
    required: true
    description: The private API key.
runs:
  using: node16
  main: ../dist/deleteAllClusters/index.js
