# See https://github.com/marketplace/actions/repo-file-sync-action for info
# about format of this file that specifies which files that will be synced
# to which repos when PRs are merged to main.

# Potentially add later:
# realm/realm-cpp
# realm-react-context
# realm-dart-samples
# realm-kotlin-samples
# realm-dotnet-samples
# realm-flipper-plugin

group:
  - files:
      - source: synced-files/LICENSE
        dest: LICENSE
      - source: synced-files/.github/workflows/Issue-Needs-Attention.yml
        dest: .github/workflows/Issue-Needs-Attention.yml
      - source: synced-files/.github/workflows/no-response.yml
        dest: .github/workflows/no-response.yml
      - source: synced-files/.github/workflows/auto-assign.yml
        dest: .github/workflows/auto-assign.yml
      - source: synced-files/.github/auto_assign.yml
        dest: .github/auto_assign.yml
      - source: synced-files/.github/advanced-issue-labeler.yml
        dest: .github/advanced-issue-labeler.yml
      - source: synced-files/.github/workflows/issue-labeler.yml
        dest: .github/workflows/issue-labeler.yml
      - source: synced-files/.github/workflows/check-pr-title.yml
        dest: .github/workflows/check-pr-title.yml
    repos: |
      realm/realm-js
      realm/realm-java
      realm/realm-dotnet
      realm/realm-swift
      realm/realm-dart
      realm/realm-kotlin
      realm/realm-studio
      realm/realm-cpp
      realm/test

# Core doesn't have issue forms yet, so don't need the issue-labeler
  - files:
      - source: synced-files/LICENSE
        dest: LICENSE
      - source: synced-files/.github/workflows/Issue-Needs-Attention.yml
        dest: .github/workflows/Issue-Needs-Attention.yml
      - source: synced-files/.github/workflows/no-response.yml
        dest: .github/workflows/no-response.yml
      - source: synced-files/.github/workflows/auto-assign.yml
        dest: .github/workflows/auto-assign.yml
      - source: synced-files/.github/auto_assign.yml
        dest: .github/auto_assign.yml
      - source: synced-files/.github/workflows/check-pr-title.yml
        dest: .github/workflows/check-pr-title.yml
    repos: |
      realm/realm-core

# Disabled check-changelog for:
# realm-js until it can handle mono-repo structure
# realm-studio as it uses a separate RELEASENOTES.md
# realm-kotlin/realm-java it is not needed
# realm/realm-core prefer to not have it
  - files:
      - source: synced-files/.github/workflows/check-changelog.yml
        dest: .github/workflows/check-changelog.yml
    repos: |
      realm/realm-dotnet
      realm/realm-swift
      realm/realm-dart
      realm/realm-cpp
      realm/test

# Don't use issue forms yet:
# realm/realm-kotlin
# realm/realm-core
# realm/realm-studio
  - files:
      - source: synced-files/.github/ISSUE_TEMPLATE/feature.yml
        dest: .github/ISSUE_TEMPLATE/feature.yml
    repos: |
      realm/realm-js
      realm/realm-java
      realm/realm-kotlin
      realm/realm-dotnet
      realm/realm-swift
      realm/realm-dart
      realm/realm-cpp

