# See https://github.com/marketplace/actions/repo-file-sync-action for info
# about format of this file that specifies which files that will be synced
# to which repos when PRs are merged to main.

group:
  repos: |
    realm/test
  files:
    - source: synced-files/LICENSE
      dest: LICENSE
    - source: synced-files/.github/workflows/issue-needs-attention.yml
      dest: .github/workflows/issue-needs-attention.yml
    - source: synced-files/.github/no-response.yml
      dest: .github/no-response.yml
    - source: synced-files/.github/ISSUE_TEMPLATE/feature.yml
      dest: .github/ISSUE_TEMPLATE/feature.yml