name: cleanup
description: Deletes all BaaS apps and Atlas clusters in a project
author: Realm
inputs:
  atlasUrl:
    required: false
    description: The Atlas url - e.g. https://cloud-qa.mongodb.com.
  realmUrl:
    required: false
    description: The MongoDB Realm url - e.g. https://realm-qa.mongodb.com.
  projectId:
    required: true
    description: The Atlas project Id.
  apiKey:
    required: true
    description: The public API key.
  privateapiKey:
    required: true
    description: The private API key.
  clusterName:
    required: false
    description: Provide a specific name of cluster that to be deleted.  If not provided, all clusters in the project will be deleted.
runs:
  using: node16
  main: ../dist/cleanup/index.js
