name: deleteCluster
description: Deletes cluster with given name in a project
author: Realm
inputs:
  atlasUrl:
    required: false
    description: The Atlas url - e.g. https://cloud-dev.mongodb.com.
  realmUrl:
    required: false
    description: The MongoDB Realm url - e.g. https://realm-dev.mongodb.com.
  projectId:
    required: true
    description: The Atlas project Id.
  apiKey:
    required: true
    description: The public API key.
  privateapiKey:
    required: true
    description: The private API key.
  clusterName:
    required: false
    description: Provide a specific name of cluster that to be deleted."
runs:
  using: node16
  main: ../dist/deleteCluster/index.js
