name: deleteOldApps
description: Deletes all BaaS apps used last more than 24 hours ago
author: Realm
inputs:
  atlasUrl:
    required: true
    description: The Atlas url - e.g. https://cloud-qa.mongodb.com.
  realmUrl:
    required: true
    description: The MongoDB Realm url - e.g. https://realm-qa.mongodb.com.
  projectId:
    required: true
    description: The Atlas project Id.
  apiKey:
    required: true
    description: The public API key.
  privateapiKey:
    required: true
    description: The private API key.
runs:
  using: node16
  main: ../dist/deleteOldApps/index.js
