name: update-changelog
description: Infers next version from the changelog and updates the changelog to reflect it.
author: Realm
inputs:
  changelog:
    required: true
    description: path to the changelog
  version:
    required: false
    description: an optional override of the version
  version-suffix:
    required: false
    description: an optional suffix to add to the generated version
  latest-version-changelog:
    required: false
    description: an optional path to store the changes from the latest version section
outputs:
  new-version:
    description: The new version as inferred from the changelog
runs:
  using: node16
  main: dist/index.js
