name: run-ios-simulator
description: Action to run an iOS app in a simulator
inputs:
  appPath:
    description: Path to app
    required: true
  bundleId:
    description: App bundle id
    required: true
  iphoneToSimulate:
    description: iPhone device to simulate
    required: false
    default: iPhone-8
  arguments:
    description: Arguments for the simulator
    required: false
    default: ""
  os:
    description: Operating System to simulate. Valid options are 'iOS' and 'tvOS'
    required: false
    default: iOS

runs:
  using: node20
  main: ./dist/index.js
