# Sync common files to other repos.
# Adjust which files are synced in the .github/sync.yml file.

name: Sync Files to repos
on:
  push:
    branches:
      - main
      - test-sync-files
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          DRY_RUN: true
          GH_PAT: ${{ secrets.REALM_CI_PAT }}
