# Sync common files to other repos.
# Adjust which files are synced in the .github/sync.yml file.

name: Sync Files to repos
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.REALM_CI_REPO_SYNC }}
          PR_LABELS: false
          DRY_RUN: false
          GIT_USERNAME: realm-ci
          GIT_EMAIL: robot@realm.io
  
