name: 'update-changelog'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: update-changelog
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm ci
          npm run all
